spring:
  profiles:
    include: oauth, aws
  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/jpashop
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver

  datasource:
    url:
    username: admin
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      leak-detection-threshold: 2000
      maximum-pool-size: 50
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      default_batch_fetch_size: 100
      format_sql: true

logging:
  slack:
    webhook-uri:
  config: classpath:logback-spring.xml
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

jwt:
  secret: 

sms:
  api:
  secret:
  

